services:
  posyandu:
    container_name: posyandu
    image: mfathoor/posyandu-api:latest
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - posyandu:/usr/src/app
    networks:
      posyandu-api:
    restart: on-failure

volumes:
    posyandu:

networks:
    posyandu-api:
      external: true
